# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  cs-fix:
    cmds:
      - bin/php numbersLadder/vendor/bin/php-cs-fixer fix {{.CLI_ARGS}}
    silent: true

  cs-fix-check:
    cmds:
      - |
        bin/php numbersLadder/vendor/bin/php-cs-fixer fix --dry-run {{.CLI_ARGS}}
    silent: true
