name: ci

on: [ push ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check code-style
        run: |
          vendor/bin/php-cs-fixer fix --dry-run

      - name: PHPUnit Tests numbersLadder
        uses: php-actions/phpunit@master
        env:
          TEST_NAME: numbersLadder
        with:
          bootstrap: vendor/autoload.php
          configuration: numbersLadder/phpunit.xml

      - name: PHPUnit Tests matrixWithRandomNumbers
        uses: php-actions/phpunit@master
        env:
          TEST_NAME: matrixWithRandomNumbers
        with:
          bootstrap: vendor/autoload.php
          configuration: matrixWithRandomNumbers/phpunit.xml
