name: numbersLadder_CI

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ github.sha }}

      - name: Install dependencies
        uses: php-actions/composer@v6

      - name: Check code-style
        run: |
          vendor/bin/php-cs-fixer fix --dry-run

      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        env:
          TEST_NAME: numbersLadder
        with:
          bootstrap: vendor/autoload.php
          configuration: numbersLadder/phpunit.xml